### ISSUE TITLE
make zkclient compile on ZK 3.3.x

### ISSUE THREAD

**Issue by junrao** [sgroschupf/zkclient#11]
Now, there is the following compilation error. 
    [javac] /Users/jrao/workspace/zkclient-0.1/src/main/java/org/I0Itec/zkclient/ZkServer.java:127: cannot find symbol
    [javac] symbol  : constructor Factory(int)
    [javac] location: class org.apache.zookeeper.server.NIOServerCnxn.Factory
    [javac]             _nioFactory = new NIOServerCnxn.Factory(port);
    [javac]                           ^
